# Generated by Django 4.2.16 on 2024-10-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='question_text',
            new_name='title_text',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
