# Generated by Django 5.1.1 on 2024-10-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_rename_title_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="file_upload",
            field=models.FileField(blank=True, null=True, upload_to="staticfiles/"),
        ),
    ]
