# Generated by Django 4.2.16 on 2024-10-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
