# Generated by Django 4.2.16 on 2024-10-23 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recipes/')),
                ('file_title', models.CharField(max_length=100)),
                ('file_description', models.TextField()),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recipes.recipe')),
            ],
        ),
    ]
