# Generated by Django 5.1.1 on 2024-10-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_recipe_rating_alter_recipe_file_upload"),
        ("recipes", "0008_recipefile"),
    ]

    operations = []
