# Generated by Django 5.1.1 on 2024-10-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_merge_20241027_1802'),
        ('recipes', '0009_merge_20241030_1320'),
    ]

    operations = [
    ]
