# Generated by Django 5.1.1 on 2024-11-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_merge_20241030_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipefile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
