# Generated by Django 5.1.1 on 2024-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_accessible_users_recipe_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pub_date",
            field=models.DateField(auto_now_add=True, verbose_name="date published"),
        ),
    ]
