# Generated by Django 5.1.2 on 2024-11-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_collaborationrequest'),
        ('recipes', '0014_recipefile_uploader'),
    ]

    operations = [
    ]
