# Generated by Django 4.2.16 on 2024-11-19 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_merge_20241113_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='file_upload',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories_text',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description_text',
            field=models.CharField(max_length=200),
        ),
    ]
