# Generated by Django 5.1.1 on 2024-12-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0016_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborationrequest",
            name="status",
        ),
    ]
