# Generated by Django 5.1.1 on 2024-12-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_remove_collaborationrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborationrequest",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="collaborationrequest",
            name="updated_at",
        ),
    ]
