# Generated by Django 4.2.16 on 2024-12-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_rating'),
        ('recipes', '0018_remove_collaborationrequest_created_at_and_more'),
    ]

    operations = [
    ]
